Simple post message to slack
wantedly/slack-notifier pull request #4
Opened 2016-09-26 12:10 UTC by koudaiii

## WHY

Simple post message to slack.

![image](https://cloud.githubusercontent.com/assets/2929102/18833826/9b8facfc-842d-11e6-800d-8d4d356fd2a6.png)

2016-09-26 12:17 UTC, dtan4 commented
Please define `bin/slack-notification` target.

```bash
$ make
make: *** No rule to make target `bin/slack-notification'.  Stop.
```

2016-09-26 12:18 UTC, dtan4 commented on main.go
> +		os.Exit(0)
This should show command line usage and exit with 1.

```
usage: slack-notification <TEXT>
```

2016-09-26 12:19 UTC, dtan4 commented on main.go
> +	req, err := http.NewRequest("POST", config.SlackWebhookURL, bytes.NewBufferString(json))
Please handle this error right here.

2016-09-26 12:20 UTC, dtan4 commented on main.go
> +	defer req.Body.Close()
If this function does nothing after here, `defer` is unnecessary.

2016-09-26 12:20 UTC, dtan4 requested changes

2016-09-26 12:50 UTC, koudaiii commented on main.go
> +	req, err := http.NewRequest("POST", config.SlackWebhookURL, bytes.NewBufferString(json))
Add parse error handling.

```
 666	func NewRequest(method, urlStr string, body io.Reader) (*Request, error) {
   667		if method == "" {
   668			// We document that "" means "GET" for Request.Method, and people have
   669			// relied on that from NewRequest, so keep that working.
   670			// We still enforce validMethod for non-empty methods.
   671			method = "GET"
   672		}
   673		if !validMethod(method) {
   674			return nil, fmt.Errorf("net/http: invalid method %q", method)
   675		}
   676		u, err := url.Parse(urlStr)
   677		if err != nil {
   678			return nil, err
   679		}
```

2016-09-26 12:50 UTC, koudaiii commented on main.go
> +	defer req.Body.Close()
Delete `defer`.

2016-09-27 01:06 UTC, dtan4 commented
You may have to run `glide update` to fill dependencies.

```bash
$ make
glide install
[WARN]  The name listed in the config file (github.com/koudaiii/slack-notifier) does not match the current location (github.com/wantedly/slack-notifier)
[WARN]  Lock file may be out of date. Hash check of YAML failed. You may need to run 'update'
```

```diff
diff --git a/glide.lock b/glide.lock
index 46572fc..ff790c1 100644
--- a/glide.lock
+++ b/glide.lock
@@ -1,4 +1,8 @@
-hash: 99cd0a7bdab40e1fe748a40176e545dbf2dbf2efb1ccacd6adaf7a84b05581ae
-updated: 2016-09-25T23:50:06.896287729+09:00
-imports: []
-devImports: []
+hash: ebc3d350539b7a3189d8ce511aa53c2729338ac39e8f11a4e2520e2371a722f5
+updated: 2016-09-27T10:05:32.483310586+09:00
+imports:
+- name: github.com/kelseyhightower/envconfig
+  version: cea086319492c3940683ea5e122aa5de70a33923
+- name: github.com/pkg/errors
+  version: 01fa4104b9c248c8945d14d9f128454d5b28d595
+testImports: []
```

2016-09-27 01:10 UTC, dtan4 requested changes

2016-09-27 01:10 UTC, dtan4 commented on main.go
> +		fmt.Println("Unable to parse slack webhook url.")
`os.Exit(1)` should exist here, shouldn't it?

2016-09-27 01:11 UTC, dtan4 commented
All error messages should be printed in stderr.

```go
fmt.Fprintln(os.Stderr, err)
```

2016-09-27 01:52 UTC, dtan4 commented
It seems no dependency is listed in `glide.yaml`. Don't you forget to do these?

```bash
$ glide get github.com/kelseyhightower/envconfig
$ glide get github.com/pkg/errors
```

2016-09-27 02:50 UTC, dtan4 requested changes

2016-09-27 02:50 UTC, dtan4 commented on config.go
> +}
Does it really need? If there is no plan to add more configuration, using `os.Getenv("SLACK_WEBHOOK_URL")` is simple and readable.

2016-09-27 06:38 UTC, koudaiii commented on config.go
> +}
slack-notifier is very simple application.
ok, I will change `LoadConfig`.

2016-09-28 01:21 UTC, koudaiii commented
please review 🙇

2016-09-28 02:59 UTC, dtan4 approved these changes

2016-09-28 03:00 UTC, dtan4 commented
LGTM 👍

2016-09-28 03:00 UTC, merged