Add deploy script
wantedly/slack-notifier pull request #5
Opened 2016-09-26 12:16 UTC by koudaiii

## WHY

ci push image in quay.io/wantedly/slack-notification.

## WHAT

- set deploy script
- set travis

2016-09-26 12:22 UTC, dtan4 commented on .travis.yml
> +addons:
Is this really required?
`glide` should be installed by `make deps`, I think.

2016-09-26 12:22 UTC, dtan4 requested changes

2016-09-26 12:27 UTC, koudaiii commented on .travis.yml
> +addons:
This commit mistake.
I will delete addons.

2016-09-26 12:29 UTC, koudaiii commented on .travis.yml
> +addons:
ooops.
I discover new mistake..
I will fix Makefile and glide.

2016-09-28 03:21 UTC, koudaiii commented
![image](https://cloud.githubusercontent.com/assets/2929102/18899723/07643bc0-8576-11e6-8ff2-b9bde9bf46e4.png)

2016-09-28 03:21 UTC, koudaiii commented
Please review 🙇

2016-09-28 03:22 UTC, dtan4 approved these changes

2016-09-28 03:22 UTC, dtan4 commented
LGTM 👍

2016-09-28 03:22 UTC, merged